#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="^(chore:|feat:|fix:|remove:|bump:|merge:) .*$"
if ! [[ $message =~ $requiredPattern ]];
then
  echo "-"
  echo "-"
  echo "-"
  echo "🚨 Wrong commit message! 😕"
  echo ""
  echo "▀███▀▀▀███▀███▀▀▀██▄ ▀███▀▀▀██▄   ▄▄█▀▀██▄ ▀███▀▀▀██▄ " 
  echo  "██    ▀█  ██   ▀██▄  ██   ▀██▄▄██▀    ▀██▄ ██   ▀██▄"
  echo  "██   █    ██   ▄██   ██   ▄██ ██▀      ▀██ ██   ▄██ " 
  echo  "██████    ███████    ███████  ██        ██ ███████"
  echo  "██   █  ▄ ██  ██▄    ██  ██▄  ██▄      ▄██ ██  ██▄"   
  echo  "██     ▄█ ██   ▀██▄  ██   ▀██▄▀██▄    ▄██▀ ██   ▀██▄" 
  echo "▄██████████████▄ ▄███▄████▄ ▄███▄ ▀▀████▀▀ ▄████▄ ▄███▄"
  echo ""
  echo "The commit message must have this format:"
  echo "<verb in imperative mood>: <what was done>"
  echo "Allowed verbs in imperative mood: chore, fix, remove, bump, merge"
  echo "Example: chore: Initial project"
  echo "-"
  echo "Your commit message was:"
  echo $message
  echo "-"
  echo "For more information, check script in .husky/commit-msg"
  echo "-"
  exit 1
fi
